### ISSUE TITLE
Quarkus build fails when using build pack "maven-quarkus" on EKS

### ISSUE THREAD

**Issue by sidkris77** [jenkins-x-buildpacks/jenkins-x-kubernetes#113]
Used the "getting-started" project from the Quarkus quickstarts. Added the entry "quarkus.native.container-build=true" in application.properties and did a jx import --pack maven-quarkus. However it fails at the Build Container Build stage with the error:

```
step-build-container-build [36mINFO[0m[0018] Taking snapshot of full filesystem...

step-build-container-build [36mINFO[0m[0025] ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 Djava.util.logging.manager=org.jboss.logmanager.LogManager"

step-build-container-build [36mINFO[0m[0025] Resolving srcs [target/lib/*]...

step-build-container-build error building image: error building stage: failed to get files used from context: copy failed: no source files specified

```

jx version is 3.2.206
Container Registry - ECR

Tried it without the entry in application.properties and also removed .dockerignore but still fails at this step. Ended up deploying it directly into EKS using the k8s yaml.

The only guide on Quarkus with JenkinsX I have found is from 2020 (https://joostvdg.github.io/jenkinsx/java-native-prod/03-quarkus/). However, thats failed too.

The Spring Pet Clinic import works fine but the Quarkus one doesnt. Any help would be appreciated. Thx.

**Comment by shiv-alana** [comment]
Here's how I solved this in case anyone else is looking to use this pack. The values.yaml and the generated Dockerfile needs to be changed.

**values.yaml**

```
# default spring boot probe path
probePath: /health

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: "/health/live"
readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: "/health/ready"
```


**Dockerfile**

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

ARG JAVA_PACKAGE=java-11-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
# Install java and the run-java script
# Also set up permissions for user `1001`
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
&& microdnf update \
&& microdnf clean all \
&& mkdir /deployments \
&& chown 1001 /deployments \
&& chmod "g+rwX" /deployments \
&& chown 1001:root /deployments \
&& curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
&& chown 1001 /deployments/run-java.sh \
&& chmod 540 /deployments/run-java.sh \
&& echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/lib/security/java.security

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
```

**Comment by sidkris77** [comment]
Here's how I solved this in case anyone else is looking to use this pack. The values.yaml and the generated Dockerfile needs to be changed.

**values.yaml**

```
# default spring boot probe path
probePath: /health

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
  # Optional distinct liveness probe path, if empty the probePath is used
  probePath: "/health/live"
readinessProbe:
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
  # Optional distinct readiness probe path, if empty the probePath is used
  probePath: "/health/ready"
```


**Dockerfile**

```
FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4

ARG JAVA_PACKAGE=java-11-openjdk-headless
ARG RUN_JAVA_VERSION=1.3.8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
# Install java and the run-java script
# Also set up permissions for user `1001`
RUN microdnf install curl ca-certificates ${JAVA_PACKAGE} \
&& microdnf update \
&& microdnf clean all \
&& mkdir /deployments \
&& chown 1001 /deployments \
&& chmod "g+rwX" /deployments \
&& chown 1001:root /deployments \
&& curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh \
&& chown 1001 /deployments/run-java.sh \
&& chmod 540 /deployments/run-java.sh \
&& echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/lib/security/java.security

# Configure the JAVA_OPTIONS, you can add -XshowSettings:vm to also display the heap size.
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 1001

ENTRYPOINT [ "/deployments/run-java.sh" ]
```
